name: Build

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get dependencies and build
      run: |
        yarn install
        yarn build

    - name: Commit files
      run: |
        cd dist/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Commit dist" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: 'production'
        directory: 'dist/'
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist/
